name: release latest lts oceanbase-ce

on:
  push:
    tags:
      - "latest-lts-oceanbase-ce-[0-9]+.[0-9]+.[0-9]+.[0-9]+-[0-9]+"
      - "latest-lts-oceanbase-[0-9]+.[0-9]+.[0-9]+.[0-9]+-[0-9]+"

jobs:
  release:
    uses: ./.github/workflows/reusable-test-and-release-oceanbase-ce.yml
    secrets: inherit
    with:
      tag_name: ${{ github.ref_name }}
      lts: true
      latest: true
