name: test oceanbase-ce

on:
  pull_request:
    paths:
      - '.github/workflows/*oceanbase-ce*.yml'
      - 'oceanbase-ce/**'
      - 'test/**/OceanBaseCETest.java'

concurrency:
  group: test-oceanbase-ce-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/reusable-build-and-test-oceanbase-ce.yml
    with:
      cache_key: test-oceanbase-ce
      version: 4.3.5.1-101000042025031818
